config/routes.rb
Rails.application.routes.draw do
  root to: 'email#index'
  get '/email/my_method', to: "email#my_method", as: "my_method_email"
  get '/email/destroy', to: "email#destroy", as: "destroy_email"
  resources :email
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/email.rb
class Email < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/email_controller.rb
class EmailController < ApplicationController
  def index
  end

  def my_method
    @email = Email.new
    current = Email.find(params[:id])
    current.read = true
    current.save
    respond_to do |format|
      format.html { redirect_to email_url}
      format.js
    end
  end

  def destroy
    Email.destroy(params[:id])
    respond_to do |format|
      format.html { redirect_to email_url}
      format.js
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/email_helper.rb
module EmailHelper
end

app/views/layouts/_email.html.erb
<h2>Object : <%= Email.find(params[:id]).object %></h2>
<hr>
<p><%= Email.find(params[:id]).body %></p>
<%= link_to "Delete email", destroy_email_path(id: params[:id]), remote: true %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EmailViewer</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>